project 'SportsBetting.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportsBetting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportsBetting
  pod 'TextFieldEffects'

  target 'SportsBettingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportsBettingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
